# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20170317_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='runner',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='runner',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
