# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20170318_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='metas',
        ),
    ]
