# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_remove_runner_metas'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='metas',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='runner',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
