# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_auto_20170318_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='metas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='runner',
            name='metas',
        ),
        migrations.AddField(
            model_name='metas',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Runner'),
        ),
    ]
