# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('www', '0010_auto_20170318_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
